name: Android CI + Qwiet AI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
      security-events: write  # keep if you later upload SARIF to code scanning

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

#      - name: Build (Gradle)
#        run: ./gradlew --no-daemon build
#        continue-on-error: false

      - name: Qwiet AI Scan
        uses: elangosenthilnathan/QwietTemplate@main
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          verbose: true
          strict: false
          wait: true
          importGitHub: false

